# Generated by Django 5.0.6 on 2024-07-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
