# Generated by Django 5.0.6 on 2024-07-18 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
